Feature/page tree code style
toeverything/AFFiNE pull request #112
Opened 2022-08-05 15:37 UTC by githbq

page-tree.ts: The underlined variable name is replaced with a lowercase hump style

2022-08-05 15:51 UTC, darkskygit requested changes

2022-08-05 15:51 UTC, darkskygit commented on libs/datasource/db-service/src/services/workspace/page-tree.ts
> +    private async fetchPageTree<TreeItem>(workspace: string) {
private functions start with an underscore

2022-08-05 15:51 UTC, darkskygit commented on libs/datasource/db-service/src/services/workspace/page-tree.ts
> +    private buildItemsForNextPage(
private functions start with an underscore

2022-08-05 15:51 UTC, darkskygit commented on libs/datasource/db-service/src/services/workspace/page-tree.ts
> +    private buildItemsForPrevPage(
private functions start with an underscore

2022-08-05 15:51 UTC, darkskygit commented on libs/datasource/db-service/src/services/workspace/page-tree.ts
> +    private buildItemsForChildPage(
private functions start with an underscore

2022-08-05 15:51 UTC, darkskygit commented on libs/datasource/db-service/src/services/workspace/page-tree.ts
> +async function updateTreeItemsTitle<
private functions start with an underscore

2022-08-06 10:36 UTC, githbq commented on libs/datasource/db-service/src/services/workspace/page-tree.ts
> +    private async fetchPageTree<TreeItem>(workspace: string) {
done

2022-08-06 10:36 UTC, githbq commented on libs/datasource/db-service/src/services/workspace/page-tree.ts
> +    private buildItemsForNextPage(
done

2022-08-06 10:36 UTC, githbq commented on libs/datasource/db-service/src/services/workspace/page-tree.ts
> +    private buildItemsForPrevPage(
done

2022-08-06 10:37 UTC, githbq commented on libs/datasource/db-service/src/services/workspace/page-tree.ts
> +    private buildItemsForChildPage(
done

2022-08-06 10:37 UTC, githbq commented on libs/datasource/db-service/src/services/workspace/page-tree.ts
> +async function updateTreeItemsTitle<
done

2022-08-06 10:38 UTC, darkskygit approved these changes

2022-08-06 11:06 UTC, merged