wip: electron providers
toeverything/AFFiNE pull request #2037
Opened 2023-04-19 16:39 UTC by pengx17

2023-04-19 18:17 UTC, Himself65 reviewed
The new blob storage example is here; you can implement it now

https://github.com/toeverything/blocksuite/pull/2169/files#diff-47e0b587214e6f48b210ff793116e9ffccaba5bad2c3fc3eba4fcdb7bb2fe931R5

2023-04-20 18:05 UTC, Himself65 requested changes
test needed

2023-04-20 18:11 UTC, Himself65 requested changes
at least you need a unit test for new provider

2023-04-21 09:51 UTC, darkskygit approved these changes

2023-04-21 10:06 UTC, merged