feat: add date picker
toeverything/AFFiNE pull request #2644
Opened 2023-06-01 08:13 UTC by JimmFly

2023-06-06 09:08 UTC, pengx17 commented
Can we have some basic test for this component?

2023-06-07 08:07 UTC, pengx17 approved these changes

2023-06-07 08:54 UTC, Himself65 requested changes
block until https://github.com/toeverything/AFFiNE/pull/2706

2023-06-07 08:55 UTC, Himself65 requested changes

2023-06-07 08:55 UTC, himself65 commented on packages/component/src/ui/date-picker/index.stories.tsx
> +import type { StoryFn } from '@storybook/react';
please move this file to `@affine/storybook`

2023-06-07 09:32 UTC, Himself65 approved these changes

2023-06-08 09:55 UTC, merged