fix: sqlite provider import sub doc db file
toeverything/AFFiNE pull request #2991
Opened 2023-07-03 16:49 UTC by pengx17

2023-07-03 18:54 UTC, pengx17 commented
@Brooooooklyn @himself65 please take a look if this approach is acceptable.

2023-07-04 02:42 UTC, himself65 requested changes
Is it possible to test the migration in e2e? Moving a `.affine` file into fixtures is acceptable.

2023-07-04 02:42 UTC, himself65 commented on .github/workflows/build.yml
> -        run: yarn workspace @affine/electron build
replace all ci actions

2023-07-04 16:33 UTC, himself65 approved these changes

2023-07-04 16:33 UTC, himself65 commented
hope everything works!

2023-07-04 18:08 UTC, merged