chore: adjustment options menu
toeverything/AFFiNE pull request #3455
Opened 2023-07-29 04:26 UTC by JimmFly

https://github.com/toeverything/AFFiNE/assets/102217452/a9e9fd41-c01d-4697-ba06-eeff010dcbd1

2023-07-29 04:31 UTC, himself65 requested changes

2023-07-29 04:31 UTC, himself65 commented on apps/core/src/components/blocksuite/workspace-header/header-right-items/editor-option-menu.tsx
> +        onClick={() => {
useCallback

2023-07-29 05:38 UTC, himself65 approved these changes
LGTM, but I think the e2e test cases also changed

2023-07-31 06:49 UTC, JimmFly commented
> LGTM, but I think the e2e test cases also changed

Apologies, I must have missed the test. I have rectified the errors.

2023-07-31 08:22 UTC, merged