feat: init share page menu
toeverything/AFFiNE pull request #3879
Opened 2023-08-21 18:07 UTC by JimmFly

Work for https://github.com/toeverything/AFFiNE/issues/3661
Added styling when AFFiNE Cloud is not enabled. The specific logic will be added in the Cloud branch after merging this PR.

https://github.com/toeverything/AFFiNE/assets/102217452/1bbe4b76-2271-4616-ab51-ece8c6b6662b

2023-08-22 10:01 UTC, Svaney-ssman requested changes
The design side has adjusted the sign-out status of the share menu. Check [design](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=11259-179690&mode=design&t=DozPvXqgRMj6tugA-4)
<img width="332" alt="image" src="https://github.com/toeverything/AFFiNE/assets/110808979/3dad4396-3a56-4207-9b89-4f5ff85dd899">

2023-08-22 12:02 UTC, JimmFly commented
![image](https://github.com/toeverything/AFFiNE/assets/102217452/efcb4360-c4c6-4644-9cb3-e7c7ec3588ce)

Done. /cc @Svaney-ssman

2023-08-23 02:10 UTC, Svaney-ssman reviewed
The UI screenshot looks good to me

2023-08-23 02:11 UTC, Svaney-ssman approved these changes

2023-08-23 03:02 UTC, himself65 approved these changes

2023-08-23 03:02 UTC, merged