feat: add open app route
toeverything/AFFiNE pull request #3899
Opened 2023-08-22 16:46 UTC by pengx17

2023-08-22 17:22 UTC, himself65 requested changes

2023-08-22 17:22 UTC, himself65 commented on apps/electron/src/main/deep-link.ts
> +import path from 'path';
node:path

2023-08-29 02:16 UTC, Garfield550 requested changes

2023-08-29 02:16 UTC, Garfield550 commented on apps/core/src/components/affine/desktop-login-modal/index.tsx
> +        Logging in ...
i18n please.

2023-08-29 05:59 UTC, pengx17 commented on apps/core/src/components/affine/desktop-login-modal/index.tsx
> +        Logging in ...
Will do. This is still wip :)

2023-08-29 10:10 UTC, himself65 reviewed
rebased to master branch

2023-08-29 20:09 UTC, himself65 approved these changes

2023-08-29 22:54 UTC, merged