Cloud Public Workspace Logic
toeverything/AFFiNE pull request #3961
Opened 2023-08-26 08:14 UTC by imf-ali

2023-08-26 08:18 UTC, imf-ali commented
Hey @himself65 , can you please have a look at this?

2023-08-26 18:25 UTC, himself65 requested changes
There's no database migration

2023-08-26 20:31 UTC, himself65 requested changes
rebase the PR to `v0.9.x-staging`

2023-08-26 20:31 UTC, himself65 commented on apps/server/schema.prisma
> +  public         WorkspaceStatus
I think it should be a computed value.

2023-08-27 11:10 UTC, imf-ali commented
> There's no database migration

Oh, I will add those

2023-08-29 01:38 UTC, closed without merging

2023-08-29 01:38 UTC, himself65 commented
Thanks for the contribution! I have rewritten the logic so that we don't need to change the schema

See: https://github.com/toeverything/AFFiNE/pull/3997