Fixes the button alignment for page and endless.
toeverything/AFFiNE pull request #3968
Opened 2023-08-27 11:33 UTC by panugothrakesh

fixes #3845

I placed the restore and delete permanently button on the page head which is more user friendly and also does not create problem to both endless and page format.

<img width="1440" alt="Screenshot 2023-08-27 at 4 57 49 PM" src="https://github.com/toeverything/AFFiNE/assets/108489118/0810d559-5e34-4317-9c83-cbde09ad5ea3">
<img width="1440" alt="Screenshot 2023-08-27 at 4 57 35 PM" src="https://github.com/toeverything/AFFiNE/assets/108489118/c55e0e85-c2cd-49bd-8729-a091779fd974">

2023-08-27 13:25 UTC, himself65 requested changes
Page head not follows the UI design. It’s a bug when we see toolbar in readonly edgeless mode. And you should open a pr for them

2023-08-27 13:28 UTC, panugothrakesh commented
> Page head not follows the UI design. It’s a bug when we see toolbar in readonly edgeless mode. And you should open a pr for them

Will look into the issue and req a new pull. Thank you!

2023-08-28 01:34 UTC, himself65 requested changes
blocking until https://github.com/toeverything/blocksuite/issues/4390

2023-10-06 04:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/toeverything/AFFiNE?pullRequest=3968) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/toeverything/AFFiNE?pullRequest=3968) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/toeverything/AFFiNE?pullRequest=3968) it.</sub>

2023-10-21 02:46 UTC, himself65 approved these changes

2023-11-20 07:01 UTC, closed without merging