fix: sign in issues
toeverything/AFFiNE pull request #4047
Opened 2023-08-30 11:27 UTC by QiShaoXuan

1. Fix countdown is reset each time switch panels
2. Fix can not set password 
3. Unified email template & modify email content
4. Modify style

2023-08-30 14:48 UTC, himself65 requested changes

2023-08-30 14:48 UTC, himself65 commented on apps/core/.webpack/config.ts
> +      // fallback: {
why

2023-08-31 03:30 UTC, QiShaoXuan commented on apps/core/.webpack/config.ts
> +      // fallback: {
Ignore it, just have try in local

2023-08-31 12:47 UTC, himself65 approved these changes

2023-08-31 13:07 UTC, merged