feat: support google login on desktop
toeverything/AFFiNE pull request #4053
Opened 2023-08-30 19:17 UTC by pengx17

Thanks for the help from @darkskygit and it turns out that we do not need to have some hacks within Electron by creating a hidden window and handling login inside of it. Now we can have it much easier:
- when signing in initated via electron, instead of directly call the signin function, popping up the login window in the browser
- when google signin finished, it can redirect to the open-app route, fetch the jwt token and send it to the desktop app
- the desktop app then accept the token and set it to the browser window

It looks like we do not need to change the electron origin after all. Will go back and fix email login as well later.

2023-08-30 19:18 UTC, himself65 requested changes

2023-08-30 19:18 UTC, himself65 commented on apps/core/src/pages/desktop-signin.tsx
> +let wip = false;
use a atom

2023-08-31 00:23 UTC, himself65 commented on apps/core/src/pages/desktop-signin.tsx
> +let wip = false;
yep

2023-08-31 00:24 UTC, himself65 commented on apps/core/src/pages/desktop-signin.tsx
> +let wip = false;
I believe we will add e2e test on this. Please make sure the UI is pure

2023-08-31 02:57 UTC, pengx17 commented
related https://github.com/toeverything/AFFiNE/issues/3944

2023-08-31 03:43 UTC, darkskygit approved these changes

2023-08-31 03:43 UTC, darkskygit approved these changes

2023-08-31 04:51 UTC, merged

2023-08-31 04:51 UTC, himself65 approved these changes