feat: send email to owner after member accepted invitation / leave workspace
toeverything/AFFiNE pull request #4152
Opened 2023-09-04 06:43 UTC by QiShaoXuan

close: https://github.com/toeverything/AFFiNE/issues/4137

2023-09-04 07:41 UTC, himself65 requested changes

2023-09-04 07:41 UTC, himself65 commented on apps/server/src/modules/workspaces/resolver.ts
> +    applyUpdate(doc, new Uint8Array(snapshot.blob));
Dont load ydoc in server side.
Add name in the request body

2023-09-04 21:36 UTC, himself65 requested changes
Add server test

2023-09-05 11:35 UTC, QiShaoXuan commented
> Add server test

Done

2023-09-05 16:56 UTC, himself65 approved these changes

2023-09-07 05:33 UTC, merged