feat: support pagination for member list
toeverything/AFFiNE pull request #4231
Opened 2023-09-06 10:49 UTC by QiShaoXuan

![image](https://github.com/toeverything/AFFiNE/assets/22772830/7fa5df8e-7b5a-4d65-bd45-9983de4300e7)

2023-09-06 17:17 UTC, Brooooooklyn commented on packages/component/src/components/member-components/invite-modal.tsx
> -  //             <MenuItem
remove it

2023-09-06 17:18 UTC, Brooooooklyn commented on apps/server/src/modules/workspaces/resolver.ts
> +      take: take || 8,
why the default value of take is 10 in frontend and 8 in the backend?

2023-09-06 17:19 UTC, Brooooooklyn commented on packages/component/src/components/member-components/invite-modal.tsx
remove it

2023-09-07 04:15 UTC, himself65 requested changes
It would be better if you added a test case

Like, register 10 users and add them into a workspace, open the workspace list, and the pagination should work

2023-09-07 07:02 UTC, QiShaoXuan commented
> It would be better if you added a test case
> 
> Like, register 10 users and add them into a workspace, open the workspace list, and the pagination should work

Added in e2e test

2023-09-12 03:37 UTC, himself65 approved these changes

2023-09-12 03:59 UTC, merged