feat: add tooltip in user & workspace setting
toeverything/AFFiNE pull request #4260
Opened 2023-09-07 07:49 UTC by QiShaoXuan

2023-09-10 19:30 UTC, himself65 requested changes

2023-09-10 19:30 UTC, himself65 commented on apps/core/src/components/affine/setting-modal/account-setting/index.tsx
> +              container: ref.current,
state, not ref

2023-09-12 16:02 UTC, pengx17 approved these changes

2023-09-13 04:36 UTC, himself65 approved these changes

2023-09-13 05:27 UTC, merged