refactor: delete page
toeverything/AFFiNE pull request #4347
Opened 2023-09-13 10:57 UTC by JimmFly

2023-09-14 12:05 UTC, hwangdev97 submitted a review, later dismissed

2023-09-15 01:30 UTC, himself65 requested changes
I'm confused about the CSS and this implementation

2023-09-15 02:06 UTC, himself65 commented
Upstream: https://github.com/toeverything/blocksuite/pull/4766

2023-09-15 06:30 UTC, himself65 approved these changes
CSS is shit, but wrong is not here

2023-09-15 06:35 UTC, hwangdev97 approved these changes

2023-09-15 06:54 UTC, pengx17 approved these changes

2023-09-16 00:55 UTC, merged