feat: add shortcut keys for toggling setting modal
toeverything/AFFiNE pull request #4433
Opened 2023-09-20 11:43 UTC by TinsFox

Add shortcut keys for toggling setting modal

⌘ + , or Ctrl + ,

Because of the use of a new design, it has resulted in many conflicts with the [previous PR](https://github.com/toeverything/AFFiNE/pull/4160). Now a new one has been opened.

2023-09-22 19:57 UTC, himself65 requested changes
I think we should move shortcut into atoms

2023-10-06 04:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/toeverything/AFFiNE?pullRequest=4433) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/toeverything/AFFiNE?pullRequest=4433) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/toeverything/AFFiNE?pullRequest=4433) it.</sub>

2023-10-12 09:11 UTC, joooye34 reviewed
@pengx17 cc and check the shortcut key usage.

2023-10-13 03:42 UTC, pengx17 requested changes
Thanks for contribution. After we refactored CMDK, you can configure keybindings in https://github.com/toeverything/AFFiNE/blob/master/apps/core/src/commands/affine-navigation.tsx#L88-L102

e.g.,

```tsx
  unsubs.push(
    registerAffineCommand({
      id: 'affine:open-settings',
      category: 'affine:navigation',
      icon: <ArrowRightBigIcon />,
      keyBinding: {
        binding: '$mod+,',
      },
      label: () => t['com.affine.cmdk.affine.navigation.open-settings'](),
      run() {
        store.set(openSettingModalAtom, {
          activeTab: 'appearance',
          workspaceId: null,
          open: true,
        });
      },
    })
  );
```

2023-10-29 15:37 UTC, closed without merging