ci: speedup electron install
toeverything/AFFiNE pull request #4457
Opened 2023-09-22 06:58 UTC by Brooooooklyn

Speed up electron build/test CI by reduce the installation packages count

2023-09-22 19:08 UTC, himself65 requested changes

2023-09-22 19:08 UTC, himself65 commented on .github/actions/setup-node/action.yml
> +    default: 'false'
unused

2023-09-28 14:48 UTC, himself65 submitted a review, later dismissed

2023-09-29 03:02 UTC, joooye34 approved these changes

2023-09-29 03:19 UTC, merged