fix(elestron): release desktop app workflow
toeverything/AFFiNE pull request #4594
Opened 2023-10-12 11:45 UTC by Brooooooklyn

2023-10-12 12:41 UTC, joooye34 submitted a review, later dismissed

2023-10-13 07:49 UTC, pengx17 submitted a review, later dismissed

2023-10-16 05:58 UTC, joooye34 approved these changes

2023-10-16 08:47 UTC, pengx17 approved these changes

2023-10-16 12:27 UTC, joooye34 approved these changes

2023-10-16 16:20 UTC, joooye34 approved these changes

2023-10-16 16:50 UTC, pengx17 approved these changes

2023-10-16 16:50 UTC, pengx17 approved these changes

2023-10-16 19:21 UTC, himself65 requested changes

2023-10-16 19:21 UTC, himself65 commented on packages/plugin-cli/package.json
> +    "vue": "^3.3.4"
?

2023-10-17 00:29 UTC, Brooooooklyn commented on packages/plugin-cli/package.json
> +    "vue": "^3.3.4"
It’s peerDependency of @vitejs/plugin-vue. Without it the build:infra command will throw error

2023-10-17 00:39 UTC, himself65 submitted a review, later dismissed

2023-10-17 06:15 UTC, joooye34 approved these changes

2023-10-17 06:35 UTC, merged