BlobStorage should provide consistent behaviour
toeverything/AFFiNE pull request #4808
Opened 2023-11-01 08:36 UTC by zhe-he

https://github.com/toeverything/AFFiNE/issues/3245

In order to avoid major changes, I defined a variable in `createSQLiteStorage` to store the type.

The default type of the blob returned in the `createStaticStorage` method is response.headers["content-type"], and I believe it does not need to be changed. If it is necessary to make changes, I list the following for reference.
```
get: async (key: string) => {
    let blob: Blob | null = null;
    if (key.startsWith('/static/')) {
        const response = await fetch(key);
        if (response.ok) blob = response.blob();
    } else if (predefinedStaticFiles.includes(key)) {
        const response = await fetch(`static/${key}`);
        if (response.ok) blob = response.blob();
    }
    if (!blob.type) {
        // Determine the type based on the blob's headers.
        const type = ...;
        blob = new Blob([blob], { type });
    }
    return blob;
},
```

2023-11-01 08:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/toeverything/AFFiNE?pullRequest=4808) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/toeverything/AFFiNE?pullRequest=4808) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/toeverything/AFFiNE?pullRequest=4808) it.</sub>

2023-11-01 17:21 UTC, lawvs requested changes
The `api.db` is a persistent storage, but the `typeMap` only exists in memory. I think the type of blob will be lost still after reloading the client.

2023-11-02 02:30 UTC, zhe-he commented
When I consider storing the type information in localStorage, it seems strange to have different storage methods for the same data. I was considering storing the type in api.db as well, but it may conflict with the user's workspaceId, which is also strange to have two storage methods for the same data - one for storing the content and another for storing the type. The most perfect solution I can think of brings us back to the initial discussion, but it would require significant changes.

I believe the perfect solution would be to modify the file `packages/frontend/electron/src/helper/db/index.ts` and change `addBlob: async (workspaceId: string, key: string, data: Uint8Array)` to `addBlob: async (workspaceId: string, key: string, data: Blob)`. (This change would affect all storage and retrieval operations.)

2023-11-10 02:05 UTC, pengx17 commented
> When I consider storing the type information in localStorage, it seems strange to have different storage methods for the same data.

Indeed, the current solution for storing blobs in different datasource is not very clean, saying when getting a blob may lose the `type` field in the blob since we only store the binary part of it.
IMO I do agree that we shall not have two storages for data and type and they could coexist in a single table.

An alternative solution is to infer the type from the binary header using libraries like [file-type](https://github.com/sindresorhus/file-type) and thus we do not need to store a separate type field for the blob. This should be fine most of the time since blob is binary, but there could be cases that blob are string types like svg/csv etc.

I am closing the PR since as @lawvs has pointed out your current solution only provide a solution that works in memory which means it will break when app reload.

2023-11-10 02:05 UTC, closed without merging