docs: docs/jobs/*
toeverything/AFFiNE pull request #489
Opened 2022-10-10 09:46 UTC by xiashuyuan

Hi,

    I read your job description carefully and update some words in unremarkable place. 

    Wish it could be closer to the habits of English speakers.

Best Wishes.

2022-10-12 08:17 UTC, CJSS commented
I have made some comments for review on this PR.

2022-10-13 01:34 UTC, CJSS commented
There are still some changes required as per my previous comments.

2022-10-13 01:35 UTC, CJSS requested changes
There are still some changes required as per my previous comments.

2022-10-13 02:25 UTC, xiashuyuan commented on docs/jobs/affine.pro-remote.md
> +-   Experience and proficiency in **JavaScript** and a **second programming language** preferably **Rust**.
Sorry, it is a mistake.

2022-10-13 02:26 UTC, xiashuyuan commented on docs/jobs/affine.pro-remote.md
> +-   Research and support **onboarding process** of new use cases for AFFiNE.pro subscribers.
You are right

2022-10-13 02:32 UTC, xiashuyuan commented on docs/jobs/affine.pro-remote.md
> +-   Love open source spirit, share our visions and work under those values.
Correct, the title ends with 'for'.

2022-10-13 02:34 UTC, xiashuyuan commented on docs/jobs/mysc.app.md
> +-   Execute performance profiling on existing systems to figure out key bottlenecks and improve their performance characteristics
I agree 'identify' is better

2022-10-13 05:56 UTC, CJSS commented
Thanks for your contribution - your PR will be included with edits in #494.

2022-10-13 05:56 UTC, closed without merging