fix(core): escape cmdk value
toeverything/AFFiNE pull request #4925
Opened 2023-11-13 12:00 UTC by JimmFly

2023-11-13 12:20 UTC, pengx17 submitted a review, later dismissed

2023-11-14 11:56 UTC, Brooooooklyn requested changes
Please `git rebase -i origin/stable` on your branch and change this pull request target to stable

2023-11-15 02:24 UTC, pengx17 submitted a review, later dismissed

2023-11-15 05:47 UTC, JimmFly commented
Current dependencies on/for this PR:
* master
  * **PR #4943** <a href="https://app.graphite.dev/github/pr/toeverything/AFFiNE/4943?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #4925** <a href="https://app.graphite.dev/github/pr/toeverything/AFFiNE/4925?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/toeverything/AFFiNE/4925?utm_source=stack-comment).

2023-11-15 05:49 UTC, closed without merging