Update mailer.ts
toeverything/AFFiNE pull request #5005
Opened 2023-11-20 13:01 UTC by saranshisatgit

Not sure this is the right approach since gmail services  is  default so this creates if the SendGrid is provided as the smtp settings !

2023-11-20 13:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/toeverything/AFFiNE?pullRequest=5005) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/toeverything/AFFiNE?pullRequest=5005) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/toeverything/AFFiNE?pullRequest=5005) it.</sub>

2023-11-30 04:18 UTC, darkskygit requested changes

2023-11-30 04:18 UTC, darkskygit commented on packages/backend/server/src/modules/auth/mailer/mailer.ts
> +        port: 587,
can use `config.auth.email.port`

2023-11-30 04:18 UTC, darkskygit commented on packages/backend/server/src/modules/auth/mailer/mailer.ts
> +    if(config.auth.email.server == 'smtp.sendgrid.net'){
can check if server not equal `smtp.gmail.com`

2024-01-30 15:45 UTC, saranshisatgit commented
@darkskygit This one could be merged thanks !

2024-02-06 10:17 UTC, saranshisatgit commented
hey @darkskygit any updates?

2024-02-19 17:45 UTC, darkskygit commented
this problem was fix by #5835 , thanks for your PR

Now you can use the following envs to define the email sender:
``` env
MAILER_HOST=
MAILER_PORT=
MAILER_USER=
MAILER_PASSWORD=
MAILER_SENDER=
```

2024-02-19 17:45 UTC, closed without merging