feat: add cache for blob query
toeverything/AFFiNE pull request #5178
Opened 2023-12-04 11:04 UTC by darkskygit

2023-12-04 11:04 UTC, darkskygit commented
Current dependencies on/for this PR:
* canary
  * **PR #5074** <a href="https://app.graphite.dev/github/pr/toeverything/AFFiNE/5074?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #5075** <a href="https://app.graphite.dev/github/pr/toeverything/AFFiNE/5075?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #5076** <a href="https://app.graphite.dev/github/pr/toeverything/AFFiNE/5076?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #5087** <a href="https://app.graphite.dev/github/pr/toeverything/AFFiNE/5087?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #5142** <a href="https://app.graphite.dev/github/pr/toeverything/AFFiNE/5142?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #5178** <a href="https://app.graphite.dev/github/pr/toeverything/AFFiNE/5178?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/toeverything/AFFiNE/5178?utm_source=stack-comment).

2023-12-11 06:28 UTC, forehalo commented on packages/backend/server/src/modules/workspaces/resolver.ts
> +@UseInterceptors(CacheInterceptor)
can we make it globally? and skip cache by default, only controllers/resolvers with `Cache` decorator go through that logic

2023-12-11 08:15 UTC, Brooooooklyn requested changes
Really don't like the idea about in-memory cache, need a complex strategy to make it valid/invalid without logic bug. Besides that, we also need a complex strategy to prevent OOM with in memory cache

2023-12-11 08:24 UTC, Brooooooklyn commented
I think cache it in redis like kv outside our app is a better solution, since we can flush the cache independently if states are unexpected or cache is full.

2023-12-11 08:34 UTC, darkskygit commented
can 

> Really don't like the idea about in-memory cache, need a complex strategy to make it valid/invalid without logic bug. Besides that, we also need a complex strategy to prevent OOM with in memory cache

i consider reuse global cache module that can switch between local/redis cache, local caching is useful for our self-hosted version

2023-12-12 07:59 UTC, darkskygit commented
> Really don't like the idea about in-memory cache, need a complex strategy to make it valid/invalid without logic bug. Besides that, we also need a complex strategy to prevent OOM with in memory cache


The current implementation can automatically switch to RedisCache according to configuration:

https://github.com/toeverything/AFFiNE/blob/94a1280768a03410b61f240f212b727cfb1da94b/packages/backend/server/src/cache/index.ts#L8-L16

2023-12-12 16:09 UTC, Brooooooklyn approved these changes

2023-12-14 10:26 UTC, merged