feat(core): allow core modules to import itself
toeverything/AFFiNE pull request #5207
Opened 2023-12-05 09:32 UTC by pengx17

2023-12-05 09:33 UTC, pengx17 commented
Current dependencies on/for this PR:
* canary
  * **PR #5207** <a href="https://app.graphite.dev/github/pr/toeverything/AFFiNE/5207?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/toeverything/AFFiNE/5207?utm_source=stack-comment).

2023-12-05 09:37 UTC, Brooooooklyn commented on packages/frontend/core/package.json
> +    "./*": "./src/*"
Use the [`imports field`](https://nodejs.org/api/packages.html#imports) to implement this feature. If you use the exports field, the reference is implemented through the symlink in node_modules. We should not rely on this behavior.

2023-12-05 09:38 UTC, Brooooooklyn requested changes
need to move self import map into `imports` field

2023-12-05 10:11 UTC, pengx17 commented on packages/frontend/core/package.json
> +    "./*": "./src/*"
I also noticed this field in `package.json`. 

I tried it but it seems there are some issues using `imports`:
- the field defined in `imports` must start with `#`. e.g., `#core`
- the files in `imports` should also be listed in `exports` for self-reference. Maybe it is because `exports` filed is used?

So we need to define some thing like this in package.json:

```json
  "imports": {
    "#core/*": "./src/*"
  },
  "exports": {
    "./*": "./src/*"
  }
```

and in ts
```ts
import { usePageHelper } from '#core/components/blocksuite/block-suite-page-list/utils';
```

---

Also it seems [self-referencing is a valid use case](https://nodejs.org/api/packages.html#self-referencing-a-package-using-its-name), if we do not care about how link works in package manager.

2023-12-06 07:51 UTC, Brooooooklyn approved these changes

2023-12-06 08:54 UTC, merged