feat: add useBlocksuiteEditor hooks
toeverything/AFFiNE pull request #5366
Opened 2023-12-21 07:27 UTC by JimmFly

2023-12-21 07:28 UTC, JimmFly commented
Current dependencies on/for this PR:
* `canary`
  * **PR #5366** <a href="https://app.graphite.dev/github/pr/toeverything/AFFiNE/5366?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/toeverything/AFFiNE/5366?utm_source=stack-comment).

2023-12-25 05:13 UTC, EYHN approved these changes

2023-12-25 07:01 UTC, CatsJuice approved these changes

2023-12-27 02:05 UTC, pengx17 commented on packages/frontend/hooks/src/use-block-suite-editor.ts
> +export const editorContainerAtom = atom<{
I think if you expose hooks, there is no point of exposing the atom any longer.
Also the API does not consider the case that two editors share the same pageId

2023-12-27 02:06 UTC, pengx17 commented on packages/frontend/hooks/src/use-block-suite-editor.ts
> +      setEditorContainer,
the name of the return value may use `useState` pattern that returns a 2-tuple.
also the name of the first param should be `editorContainer`

2023-12-27 02:07 UTC, pengx17 commented on packages/frontend/component/src/components/block-suite-editor/index.tsx
> +  const { setEditorContainer } = useBlocksuiteEditor(page.id);
Should remove the editor instance when unmount

2023-12-27 02:08 UTC, pengx17 requested changes
Please resolve my comments

2023-12-27 08:39 UTC, pengx17 commented
So the new impl does not support multiple editors?

2023-12-27 08:44 UTC, JimmFly commented
> So the new impl does not support multiple editors?

Apologies, it seems I’ve misconstrued your meaning. I interpreted the comment as suggesting that the editor atom didn’t require correspondence with the pageid.

>Also the API does not consider the case that two editors share the same pageId

2023-12-27 09:00 UTC, pengx17 approved these changes

2023-12-28 08:44 UTC, merged