fix(core): open ai chat for first time
toeverything/AFFiNE pull request #7291
Opened 2024-06-20 12:15 UTC by fundon

2024-06-20 12:15 UTC, fundon commented
* **#7291** <a href="https://app.graphite.dev/github/pr/toeverything/AFFiNE/7291?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `canary`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @fundon and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-20 12:17 UTC, JimmFly approved these changes

2024-06-20 12:30 UTC, L-Sun requested changes

2024-06-20 12:30 UTC, L-Sun commented on packages/frontend/core/src/pages/workspace/detail-page/detail-page.tsx
> -    AIProvider.slots.requestContinueInChat.on(() => {
This slot is used by ai answer panel
![image](https://github.com/toeverything/AFFiNE/assets/20479050/da6060c7-2ced-4407-9d2f-a9e80bae46fe)

2024-06-20 12:43 UTC, L-Sun approved these changes

2024-06-21 01:51 UTC, EYHN approved these changes

2024-06-21 02:46 UTC, merged