fix  #5813
toeverything/AFFiNE pull request #7401
Opened 2024-07-01 16:16 UTC by dhillonsahil

Changes Made
### 1. Added autoFocus Property to ConfirmModalProps:

Enhanced the ConfirmModalProps interface to include an optional autoFocus property within the confirmButtonOptions. This allows the confirm button to be auto-focused when the modal is opened.

```
export interface ConfirmModalProps extends ModalProps {
  confirmButtonOptions?: ButtonProps & { autoFocus?: boolean }; // Added autoFocus here
  ...
}
```
### 2. Set autoFocus Attribute on the Confirm Button in ConfirmModal Component:

Updated the ConfirmModal component to pass the autoFocus attribute to the Button component used for the confirm action. This ensures the confirm button is focused automatically, allowing users to press the Enter key to confirm.

`<Button onClick={onConfirmClick} autoFocus={confirmButtonOptions?.autoFocus} {...confirmButtonOptions}></Button>`

Summary

These changes improve the user experience by allowing the delete (confirm) button in the confirmation modal to be auto-focused. As a result, users can now press the Enter key to activate the confirm button without needing to manually click it.

2024-07-01 16:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/toeverything/AFFiNE?pullRequest=7401) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/toeverything/AFFiNE?pullRequest=7401) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/toeverything/AFFiNE?pullRequest=7401) it.</sub>

2024-07-08 03:35 UTC, pengx17 reviewed
Some suggestions
- remove autoFocus prop for `confirmButtonOptions`. This should be default for confirm buttons if we want this behavior.
- affine's button does not render focus outline rings which gives no indicator that which button is currently focused. It may not be a good idea to have this fix alone without focus rings. cc @zanwei @CatsJuice

2024-07-08 06:36 UTC, CatsJuice requested changes

2024-07-08 06:36 UTC, CatsJuice commented on packages/frontend/component/src/ui/modal/confirm-modal.tsx
> +  confirmButtonOptions?: ButtonProps & { autoFocus?: boolean }; // Add autoFocus here
The ﻿autoFocus property already exists on ﻿ButtonProps, so the changes made in this PR are unnecessary. Furthermore, I haven't seen any use of this specified property in this PR.

2024-07-11 09:35 UTC, CatsJuice commented
> Some suggestions
> 
> * remove autoFocus prop for `confirmButtonOptions`. This should be default for confirm buttons if we want this behavior.
> * affine's button does not render focus outline rings which gives no indicator that which button is currently focused. It may not be a good idea to have this fix alone without focus rings. cc @zanwei @CatsJuice

We can't remove because it's included in `ButtonProps`

2024-07-20 10:50 UTC, closed without merging