feat: add copilot metrics
toeverything/AFFiNE pull request #8455
Opened 2024-10-08 10:50 UTC by darkskygit

fix CLOUD-73

2024-10-09 10:21 UTC, forehalo commented on packages/backend/server/src/fundamentals/metrics/utils.ts
> +export const CallThrowableCounter = (
the logic could be merged into `CallCounter`(including `CallTimer`) because only important fn calls will be monitored. the error count and time do matter

2024-10-09 10:21 UTC, forehalo commented on packages/backend/server/src/fundamentals/metrics/utils.ts
> +      const errorCount = metrics[scope].counter(name, {
move to catch block

2024-10-11 08:43 UTC, darkskygit commented
* **#8455** <a href="https://app.graphite.dev/github/pr/toeverything/AFFiNE/8455?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `canary`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @darkskygit and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-16 04:59 UTC, forehalo requested changes
rebase

2024-10-18 03:29 UTC, forehalo approved these changes

2024-10-18 03:43 UTC, merged