feat(core): remember the scroll position of doc when routing forward and backward
toeverything/AFFiNE pull request #8631
Opened 2024-10-29 14:54 UTC by JimmFly

close AF-1011

https://github.com/user-attachments/assets/d2dfeee2-926f-4760-b3fb-8baf5ff90aa9

2024-10-29 14:54 UTC, JimmFly commented
* **#8631** <a href="https://app.graphite.dev/github/pr/toeverything/AFFiNE/8631?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `canary`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @JimmFly and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-31 09:22 UTC, pengx17 requested changes

2024-10-31 09:22 UTC, pengx17 commented on packages/frontend/core/src/desktop/pages/workspace/detail-page/detail-page.tsx
> +  const scrollPosition = view.scrollPositions.get(view.history.location);
Move this inside handlers, eg.
 
```ts
  const handleScroll = useCallback(
    (e: React.UIEvent<HTMLDivElement>) => {
      const scrollTop = e.currentTarget.scrollTop;
      const scrollPosition = view.getScrollPosition(view.history.location);

      const hasScrollTop = scrollTop > 0;
      setHasScrollTop(hasScrollTop);
      if (scrollPosition !== scrollTop && scrolled) {
        view.setScrollPosition(scrollTop);
      }
    },
    [scrolled, view]
  );
```

2024-11-01 01:46 UTC, pengx17 commented on packages/frontend/core/src/desktop/pages/workspace/detail-page/detail-page.tsx
> +  const [scrolled, setScrolled] = useState(false);
change to useRef. scrolled value changes may not retrigger the useEffect

2024-11-01 02:04 UTC, pengx17 commented on packages/frontend/core/src/modules/workbench/view/browser-adapter.ts
>      view.history.push(newLocation, 'fromBrowser');
skip if from view?

2024-11-01 02:04 UTC, pengx17 approved these changes

2024-11-01 02:04 UTC, pengx17 reviewed
[![clap](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/WjlTemxb6oA4PgZFmj08/10e8450b-40ef-48ee-a846-327aa2dee627/clap.gif)](https://app.graphite.dev//settings/meme-library?org=toeverything)

2024-11-05 07:15 UTC, merged