chore: bump BlockSuite version
toeverything/AFFiNE pull request #910
Opened 2023-02-08 10:08 UTC by thorseraq

0.4.0-alpha.2...0.4.0-20230207201257-d147e8c

2023-02-08 13:03 UTC, Himself65 approved these changes

2023-02-09 02:46 UTC, thorseraq commented
We can't disable experimental warnings throughout config, it's discussed here: https://github.com/vercel/next.js/discussions/32192#discussion-3726623. One way can work, by patching next package

<img width="887" alt="image" src="https://user-images.githubusercontent.com/20554850/217704379-0266234c-b0ea-4047-9601-84e3c1ed3876.png">

2023-02-09 06:51 UTC, Himself65 approved these changes

2023-02-09 12:17 UTC, lawvs requested changes
the patch contains a lot of unexpected stuff

2023-02-09 12:19 UTC, darkskygit commented on patches/next@13.1.0.patch
> ++<?xml version="1.0" encoding="UTF-8"?>
redundant idea configuration files

2023-02-09 19:06 UTC, Himself65 approved these changes

2023-02-09 19:09 UTC, merged