feat: team mail sender
toeverything/AFFiNE pull request #9104
Opened 2024-12-11 09:30 UTC by darkskygit

2024-12-11 09:30 UTC, darkskygit commented
* **#9104** <a href="https://app.graphite.dev/github/pr/toeverything/AFFiNE/9104?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/toeverything/AFFiNE/9104?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `canary`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-12 03:02 UTC, forehalo commented on packages/backend/server/src/core/workspaces/resolvers/workspace.ts
> -    @Args('workspaceName') workspaceName: string,
make it nullable and mark deprecated

2024-12-12 03:02 UTC, forehalo approved these changes

2024-12-12 05:17 UTC, Brooooooklyn requested changes
pr title scope

2024-12-12 05:57 UTC, Brooooooklyn approved these changes

2024-12-12 07:50 UTC, merged